// <auto-generated />
namespace MusicCollector.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class release : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(release));
        
        string IMigrationMetadata.Id
        {
            get { return "201805192221520_release"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
